site_name: DWEC Bilingual

nav:
  - Home: index.md
  - U1 - Frontend Tools: 01_frontend_introduction/README.md
  - U2 - JS Fundamentals: 02_js_fundamentals/README.md
  - U3 - Objects, Classes and Arrays: 03_objects_arrays/README.md
  - U4 - Manipulating the DOM: 04_DOM/README.md
  - U5 - Events and Forms: 05_events_forms/README.md
  - U6 - AJAX: 06_AJAX/README.md
  - U7 - Local Storage: 07_local_storage/README.md

theme: 
  logo: 01_frontend_introduction/img/JSEvol.png
  name: material
  features:
    - content.code.copy
    - content.tabs.link
  navigation_depth: 3
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to automatic mode

extra_css:
  - 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css'
  - 'css/custom.css'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      toc_depth: 3
